from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem, EnergySystem
from dots_infrastructure.EsdlHelperFunctions import EsdlHelperFunctions

# This file is generated, DO NOT edit this file!

class EuphemiaMarketClearingBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()
        self.esdl_obj_mapping : dict[EsdlId, EnergySystem]= {}

        
        # Calculation: clear_market
        self.clear_market_period_seconds = 86400
        clear_market_inputs = [
        
            SubscriptionDescription(esdl_type="AggregatedConsumer",
                                    input_name="community_net_vector",
                                    input_unit="kWh",
                                    input_type=h.HelicsDataType.VECTOR),
            SubscriptionDescription(esdl_type="AggregatedConsumer",
                                    input_name="community_price_vector",
                                    input_unit="EUR/kWh",
                                    input_type=h.HelicsDataType.VECTOR),
        ]
        clear_market_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="EnergySystem",
                                    output_name="mcp_vector",
                                    output_unit="EUR/MWh", 
                                    data_type=h.HelicsDataType.VECTOR),
        ]
        clear_market_information = HelicsCalculationInformation(
            time_period_in_seconds=86400,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="clear_market", 
            inputs=clear_market_inputs, 
            outputs=clear_market_outputs, 
            calculation_function=self.clear_market
        )
        self.add_calculation(clear_market_information)

    def init_calculation_service(self, energy_system: EnergySystem):
        all_esdl_objs = EsdlHelperFunctions.get_all_esdl_objects_from_type(energy_system.eAllContents(), EnergySystem)
        for esdl_obj in all_esdl_objs:
            if hasattr(esdl_obj, "id"):
                self.esdl_obj_mapping[esdl_obj.id] = esdl_obj

    
    def clear_market(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    